# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('item_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ASIN', models.CharField(max_length=50)),
                ('gamestopurl', models.CharField(max_length=200)),
                ('targeturl', models.CharField(max_length=200)),
                ('walmartid', models.CharField(max_length=50)),
            ],
        ),
    ]
