# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170302_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='target_available',
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='target_price',
        ),
    ]
