# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170303_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='targeturl',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='ebay_available',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='ebay_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='ebayid',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
